### ISSUE TITLE
Temel mesaj tiplerinin mock arayüzü

### ISSUE THREAD

**Issue by furkandinc** [squaddro/Touricity-Server#14]
Gelen json isteklerine hangi json sınıfları ile cevap döndürüleceğini simüle eden bir mock arayüzü oluşturulacaktır. Burada oluşturulan örnek mesajlar anlamlı olmalıdır. Fakat geçerliliği olmamalıdır. Yani herhangi bir id/username'nin database'te bir karşılığı olmamalıdır. Aşağıda hangi yoldan nasıl bir cevap alabileceğinin örneği verilmiştir. 

/mock
 - var olan mock arayüzlerinin path listesini döner
 - örnek { Stop: "/mock/stop", Path: "/mock/path" ... }

/mock/stop
 - anlamlı bir stop sınıfına uygun mesaj döndürülür
 - örnek { stop_id: "c09fc4c0-cee5-4ce7-bf35-448917e7d8e9", location_id: "5c0ca3bb-638d-41ef-8e36-53a5b113d044" }

Ek özellik olarak ?random=true ise mesajların içerikleri rastgele oluşturulacaktır. Stringler için database'te tanımlı maksimum boyuta göre sınırlandırılacaktır.
/mock/stop?random=true
 - örnek { stop_id: "47x474bcfpIEDWthjjskpclGFLVeXHTsR6qt", location_id: "8wPRFeBkfNGo6F6KMv6k5jWnm3SK0Fsj7BTY" }

**Comment by YKakdas** [comment]
![WhatsApp Image 2020-01-16 at 18 19 47 (1)](https://user-images.githubusercontent.com/43451457/72537433-32ad8c00-388d-11ea-9283-f541a6eaca55.jpeg)
